import QtQuick

QtObject {
    property int barTopMargin: 8
    property int barSideMargin: 16
    property int pillHeight: 36
    property int pillRadius: 18
    property int pillHPadding: 10
    property int windowPillHPadding: 15
    property int trayIconSize: 21
    property int itemSpacing: 4
    property int traySpacing: 10
    property int groupSpacing: 6
    property int popupRadius: 18
    property int popupAnimationMs: 190
    property int popupAnimationOffset: 18
    property int memoryPillWidth: 88
    property int cpuPillWidth: 82
    property int quickSettingsWidth: 390
    property int quickSettingsEdgeWidth: 96
    property int musicWorkspaceSpacing: 15
    property int musicPillWidth: 280
    property int musicPopupWidth: 760
    property int musicPopupHeight: 500
    property int musicPopupMargin: 28
    property int musicPopupSpacing: 28
    property int musicInfoColumnWidth: 324
    property int musicCoverSize: 250
    property int musicCoverRadius: 16
    property int musicCoverX: 37
    property int musicCoverY: 40
    property int musicInfoSpacerHeight: 45
    property int musicInfoSpacing: 8
    property int musicControlSpacing: 10
    property int musicProgressHeight: 12
    property int musicProgressWaveLength: 22
    property real musicProgressWaveAmplitude: 2.0
    property real musicProgressKnobRadius: 5.0
    property int musicPillTextMargin: 12
    property int musicPillTextSpacing: 8
    property int musicPillIconTitleSpacing: 20
    property int musicPillLyricScrollDelay: 1000
    property int musicPillLyricScrollEndDelay: 800
    property int musicPillLyricScrollMsPerPixel: 35
    property int musicPopupOffsetY: 14
    property int musicLyricHeightReduction: 30
    property int musicLyricAnimationMs: 160
    property int musicPositionRefreshInterval: 250
    property int musicLyricRefreshInterval: 2000
    property int musicPillIconFontSize: 12
    property int musicPopupFallbackIconFontSize: 34
    property int musicTitleFontSize: 18
    property int musicArtistFontSize: 12
    property int musicTimeFontSize: 11
    property int musicTimeWidth: 38
    property int musicControlFontSize: 27
    property int musicPlayFontSize: 31
    property int musicLyricActiveFontSize: 22
    property int musicLyricInactiveFontSize: 19
    property int musicLyricItemVPadding: 20
    property int musicLyricMaxEntries: 120
    property real musicLyricHighlightPosition: 0.25
    property real musicLyricLineHeight: 1.08
    property real musicActiveOverlayOpacity: 0.28
    property int barFontSize: 16
    property int archIconFontSize: 14
    property int toastWidth: 360
    property int toastTopMargin: 66
    property int toastRadius: 20
    property int toastAnimationMs: 210
    property int toastDurationMs: 1800
    property int toastProgressHeight: 5
}
