import QtQuick

QtObject {
    readonly property var presets: [
        {
            name: "Tela Cyan",
            pill: "#331c3435",
            section: "#330b1d1f",
            active: "#99517879",
            text: "#efffff",
            muted: "#66efffff",
            accent: "#9cf7f2",
            accent2: "#77deda",
            bluetooth: "#b7fffb",
            clock: "#d7fffd",
            cpu: "#6dd3cf",
            memory: "#c5fffb",
            window: "#aef2ee"
        },
        {
            name: "Sakura",
            pill: "#33302734",
            section: "#3317131a",
            active: "#99543a51",
            text: "#fff7fb",
            muted: "#66fff7fb",
            accent: "#ffb3d1",
            accent2: "#ff8fbd",
            bluetooth: "#ffc8df",
            clock: "#ffe2ee",
            cpu: "#ff7aaa",
            memory: "#ffd0e2",
            window: "#ffbfd9"
        },
        {
            name: "Mint",
            pill: "#33242d29",
            section: "#33111815",
            active: "#99446d59",
            text: "#f5fff9",
            muted: "#66f5fff9",
            accent: "#a8f7c6",
            accent2: "#7edfa9",
            bluetooth: "#c7ffd9",
            clock: "#defee8",
            cpu: "#68c990",
            memory: "#d6ffe3",
            window: "#bdf2cf"
        },
        {
            name: "Amber",
            pill: "#33342d24",
            section: "#331a1510",
            active: "#99745b2f",
            text: "#fffaf0",
            muted: "#66fffaf0",
            accent: "#ffd27d",
            accent2: "#ffbd5e",
            bluetooth: "#ffe0a8",
            clock: "#fff0c2",
            cpu: "#e8a94b",
            memory: "#ffe8a3",
            window: "#ffe8ad"
        },
        {
            name: "Nord",
            pill: "#33242f3c",
            section: "#33101620",
            active: "#99495e78",
            text: "#eceff4",
            muted: "#669aa7bd",
            accent: "#88c0d0",
            accent2: "#6faac2",
            bluetooth: "#a6d7e8",
            clock: "#d8f0f7",
            cpu: "#5f9bb6",
            memory: "#c4e9f2",
            window: "#9fd2e2"
        },
        {
            name: "Grape",
            pill: "#332b2738",
            section: "#3315111d",
            active: "#995b4a82",
            text: "#faf5ff",
            muted: "#66faf5ff",
            accent: "#c9a7ff",
            accent2: "#aa86ee",
            bluetooth: "#dfc8ff",
            clock: "#ddd0ff",
            cpu: "#9469d7",
            memory: "#eadcff",
            window: "#d6b8ff"
        },
        {
            name: "Blue",
            pill: "#33232d3a",
            section: "#33101722",
            active: "#99425f8f",
            text: "#f4f9ff",
            muted: "#66f4f9ff",
            accent: "#8ecbff",
            accent2: "#67b6f2",
            bluetooth: "#b9dcff",
            clock: "#d8efff",
            cpu: "#559fe0",
            memory: "#c9e7ff",
            window: "#b7dcff"
        },
        {
            name: "Purple",
            pill: "#332c2638",
            section: "#33171122",
            active: "#99624b91",
            text: "#fbf5ff",
            muted: "#66fbf5ff",
            accent: "#c59cff",
            accent2: "#ac82ee",
            bluetooth: "#dfc0ff",
            clock: "#ead8ff",
            cpu: "#9a6fde",
            memory: "#eedcff",
            window: "#dec0ff"
        },
        {
            name: "Green",
            pill: "#33242f28",
            section: "#33111915",
            active: "#99467455",
            text: "#f4fff7",
            muted: "#66f4fff7",
            accent: "#9cf2b6",
            accent2: "#72d99a",
            bluetooth: "#c4ffd6",
            clock: "#d7ffe2",
            cpu: "#5fc581",
            memory: "#d8ffe4",
            window: "#c8f7b7"
        }
    ]
}
